
import javax.swing.JOptionPane;

public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingLabel = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loading");
        setBackground(new java.awt.Color(255, 204, 0));
        setPreferredSize(new java.awt.Dimension(1700, 900));

        BackGround.setBackground(new java.awt.Color(255, 204, 51));
        BackGround.setMinimumSize(new java.awt.Dimension(1000, 900));
        BackGround.setPreferredSize(new java.awt.Dimension(1000, 900));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BackGround.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 600, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/line-removebg-preview (2).png"))); // NOI18N
        BackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel2.setText("BLOOD BANK MANAGEMENT SYSTEM");
        BackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 670, 60));

        LoadingBar.setAlignmentX(0.2F);
        BackGround.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1000, 20));

        LoadingLabel.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        LoadingLabel.setText("Loading......");
        BackGround.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 40));

        LoadingValue.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        LoadingValue.setText("0%");
        BackGround.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 80, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash (1) (1) (1) (1) (1) (1) (1).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        BackGround.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1000, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
        
        try
        {
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(100);
                sp.LoadingValue.setText(i +"%");
                
                if(i==10)
                {
                   sp.LoadingLabel.setText("Turning On Modules...."); 
                }
                if(i==20)
                {
                   sp.LoadingLabel.setText("Loading Modules...."); 
                }
                if(i==50)
                {
                   sp.LoadingLabel.setText("Connecting to Database...."); 
                }
                if(i==70)
                {
                   sp.LoadingLabel.setText("Connection Successful"); 
                }
                if(i==90)
                {
                   sp.LoadingLabel.setText("Redirecting to Login Page....");
                   
                }
                sp.LoadingBar.setValue(i);
//                System.out.println("the "+sp);
                if(i==100){ 
                sp.setVisible(false);
                new Homepage().setVisible(true);
                }
            }
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
